name: mojap package PyPI publisher
description: publishes the given repository to PyPI


runs:
  using: composite
  steps:
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: install poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: publish to PyPI
      shell: bash
      run: poetry publish --build
